[package]
name = "taxicab"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
bincode = "2.0.1"
tokio = {version="1", features =["full"]}
tokio-util = {version="0.7.0", features=["full"]}
futures = { version = "0.3.0", features = ["thread-pool"]}
tokio-stream = "0.1.17"
